version: 2.1


executors:
  docker:
    docker:
      - image: circleci/python:3.8

jobs:
  build:
    executor: docker
    steps:
      - checkout
      - restore_cache:
          keys:
            - asn1scc-{{ checksum "Dockerfile" }}
      - setup_remote_docker:
          version: 18.06.1-ce
      - run:
          name: Build Docker Image
          command: |
            docker build -t asn1scc:latest .
          when:
            not:
              steps:
                - restore_cache:
                    keys:
                      - asn1scc-{{ checksum "Dockerfile" }}
      - run:
          name: Run test cases
          command: |
            docker run -it -v $(pwd):/root/asn1scc asn1scc /bin/bash -c 'cd /root/asn1scc ; echo "hello" ; ./circleci-build.sh'
      - save_cache:
          key: asn1scc-{{ checksum "Dockerfile" }}
          paths:
            - /root/.cache/pip
            - /root/.cache/apt
            - /root/.cache/docker
            - /root/.cache/npm
      - persist_to_workspace:
          root: /root
          paths:
            - .
  resource_class: xlarge

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
